CREATE DATABASE covid_info;

USE covid_info;

CREATE TABLE users (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE comments (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  user_id INT(11),
  comment TEXT,
  date_posted DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
